package com.popkter.collector

import com.senseauto.basiclibrary.entity.Poi


val NOVEL_DATA_LIST = listOf(
    "幽灵：上帝，我下次投胎想和天使一样全身洁白，并且带着一对翅膀，但我仍然想吸血。\n" + "上帝：那你投胎做护舒宝吧。",
    "有个朋友第一次勤工俭学在公园里卖冰棍，不好意思吆喝；这时候突然有一人在那里大喊：“卖冰棍儿~~~~卖冰棍儿~~”。那朋友一听，心里可高兴了，就跟着喊：“我也是~~~~我也是~~~~”。",
    "蚂蚁和大象结婚不久，大象就死了。蚂蚁一边埋大象，一边痛哭：“亲爱的，你怎么这么早去了，我这辈子不干别的，就埋你了！”",
    "男生暗恋一女生 鼓气勇气问那女生喜欢什么样的男生\n “投缘的”女生答 ，连问几遍都是一样的答案\n该男生泄气道：“头扁的行不行”。",
    "一日,我上气不接下气追赶末班车，一边追一边喊：师傅!师傅等等我呀~\n车窗突然有名乘客探出头来，慢条斯理的对着我说：悟空．你就别追了",
    "某天考生物，其中有一题是看鸟的腿猜出鸟的名字。某生实在不懂，生气的把卷子一撕准备离开考场。监考老师很生气于是问他：“你是哪班的，叫什么名字？”某生把裤腿一掀，说：“你猜啊你猜啊。”",
    "漂亮的蒙古族女演员表演完后，领导上台接见，接着她的手，问寒问暖，半天也不肯放，亲切问道：你叫什么名字？该女演员激动地回答道“玛勒格碧.松首”",
    "一个人买了一个只会说俩字谁呀的鹦鹉，有一天主人不在家，有个换煤气的来敲门。\n鹦鹉：谁呀。\n答：换煤气的\n鹦鹉：谁呀。\n答：换煤气的\n……\n主人宅门 knock door\n门内：换煤气的"
)

const val THINK_DESC = "正在思考..."

const val SCENE_DESC = "麦当劳（McDonald's）是全球最大的快餐连锁企业之一，以其标志性的金色拱门“M”为标志。它提供各种汉堡、薯条、鸡肉产品、早餐食品、软饮料、甜点和沙拉等。麦当劳以其快速服务、标准化产品和广泛的市场覆盖而闻名，业务遍布全球100多个国家和地区。"

const val MUSIC_ITEM_COVER = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0"

val POI_LIST = listOf(
    Poi(
        cover = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0",
        name = "麦当劳1",
        type = "美食",
        score = 4,
        distance = 100,
        address = "北京市朝阳区北三环西路19号",
        latitude = 39.914,
        longitude = 116.391
    ),
    Poi(
        cover = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0",
        name = "麦当劳2",
        type = "美食",
        score = 4,
        distance = 100,
        address = "北京市朝阳区北三环西路19号",
        latitude = 39.914,
        longitude = 116.391
    ),
    Poi(
        cover = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0",
        name = "麦当劳3",
        type = "美食",
        score = 4,
        distance = 100,
        address = "北京市朝阳区北三环西路19号",
        latitude = 39.914,
        longitude = 116.391
    ),
    Poi(
        cover = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0\n",
        name = "麦当劳4",
        type = "美食",
        score = 4,
        distance = 100,
        address = "北京市朝阳区北三环西路19号",
        latitude = 39.914,
        longitude = 116.391
    ),
    Poi(
        cover = "https://ts1.cn.mm.bing.net/th/id/R-C.18c1f8dcff8dfde7cd4339b139fe03cd?rik=9OgD0DdBLzD9UQ&riu=http://officialwebsitestorage.blob.core.chinacloudapi.cn/public/files/attachment/M+logo-red.jpg&ehk=Pyw/dZIf2z2/XCaVWP586p3rG48sEJp0qZLhhAePsMA=&risl=&pid=ImgRaw&r=0",
        name = "麦当劳5",
        type = "美食",
        score = 4,
        distance = 100,
        address = "北京市朝阳区北三环西路19号",
        latitude = 39.914,
        longitude = 116.391
    )
)

val WEATHER_DATA = """
    {
        "queryCost": 1,
        "latitude": 31.2552,
        "longitude": 121.475,
        "resolvedAddress": "中国上海",
        "address": "shanghai",
        "timezone": "Asia/Shanghai",
        "tzoffset": 8,
        "days": [
            {
                "datetime": "2024-10-10",
                "datetimeEpoch": 1728489600,
                "tempmax": 24,
                "tempmin": 15.1,
                "temp": 21.5,
                "feelslikemax": 24,
                "feelslikemin": 15.1,
                "feelslike": 19.5,
                "dew": 11.6,
                "humidity": 62.6,
                "precip": 0,
                "precipprob": 0,
                "precipcover": 0,
                "preciptype": null,
                "snow": 0,
                "snowdepth": 0,
                "windgust": 13,
                "windspeed": 15.1,
                "winddir": 2.8,
                "pressure": 1016.9,
                "cloudcover": 69.5,
                "visibility": 15.4,
                "solarradiation": 207.4,
                "solarenergy": 18,
                "uvindex": 8,
                "severerisk": 10,
                "sunrise": "05:53:34",
                "sunriseEpoch": 1728510814,
                "sunset": "17:28:12",
                "sunsetEpoch": 1728552492,
                "moonphase": 0.25,
                "conditions": "Partially cloudy",
                "description": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "stations": [
                    "ZSSS",
                    "ZSPD"
                ],
                "source": "comb"
            },
            {
                "datetime": "2024-10-11",
                "datetimeEpoch": 1728576000,
                "tempmax": 24.8,
                "tempmin": 17.4,
                "temp": 24.7,
                "feelslikemax": 24.8,
                "feelslikemin": 17.4,
                "feelslike": 20.7,
                "dew": 12.8,
                "humidity": 61.5,
                "precip": 0,
                "precipprob": 0,
                "precipcover": 0,
                "preciptype": null,
                "snow": 0,
                "snowdepth": 0,
                "windgust": 18,
                "windspeed": 13.3,
                "winddir": 31.4,
                "pressure": 1019,
                "cloudcover": 24.5,
                "visibility": 24.1,
                "solarradiation": 232.3,
                "solarenergy": 20.1,
                "uvindex": 8,
                "severerisk": 10,
                "sunrise": "05:54:14",
                "sunriseEpoch": 1728597254,
                "sunset": "17:27:01",
                "sunsetEpoch": 1728638821,
                "moonphase": 0.25,
                "conditions": "Partially cloudy",
                "description": "Becoming cloudy in the afternoon.",
                "icon": "partly-cloudy-day",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-12",
                "datetimeEpoch": 1728662400,
                "tempmax": 25.2,
                "tempmin": 18.4,
                "temp": 21.6,
                "feelslikemax": 25.2,
                "feelslikemin": 18.4,
                "feelslike": 21.6,
                "dew": 13.7,
                "humidity": 61.6,
                "precip": 0,
                "precipprob": 0,
                "precipcover": 0,
                "preciptype": null,
                "snow": 0,
                "snowdepth": 0,
                "windgust": 26.3,
                "windspeed": 15.8,
                "winddir": 81.1,
                "pressure": 1021.2,
                "cloudcover": 77.3,
                "visibility": 24.1,
                "solarradiation": 213.6,
                "solarenergy": 18.5,
                "uvindex": 8,
                "severerisk": 10,
                "sunrise": "05:54:54",
                "sunriseEpoch": 1728683694,
                "sunset": "17:25:50",
                "sunsetEpoch": 1728725150,
                "moonphase": 0.32,
                "conditions": "Partially cloudy",
                "description": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-13",
                "datetimeEpoch": 1728748800,
                "tempmax": 25.8,
                "tempmin": 21.1,
                "temp": 22.8,
                "feelslikemax": 25.8,
                "feelslikemin": 21.1,
                "feelslike": 22.8,
                "dew": 16.4,
                "humidity": 67.3,
                "precip": 0.1,
                "precipprob": 19.4,
                "precipcover": 4.17,
                "preciptype": [
                    "rain"
                ],
                "snow": 0,
                "snowdepth": 0,
                "windgust": 29.9,
                "windspeed": 15.8,
                "winddir": 101.1,
                "pressure": 1019.4,
                "cloudcover": 95.2,
                "visibility": 24.1,
                "solarradiation": 94,
                "solarenergy": 8.2,
                "uvindex": 7,
                "severerisk": 10,
                "sunrise": "05:55:35",
                "sunriseEpoch": 1728770135,
                "sunset": "17:24:40",
                "sunsetEpoch": 1728811480,
                "moonphase": 0.35,
                "conditions": "Overcast",
                "description": "Cloudy skies throughout the day.",
                "icon": "cloudy",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-14",
                "datetimeEpoch": 1728835200,
                "tempmax": 24.3,
                "tempmin": 21.2,
                "temp": 22.3,
                "feelslikemax": 24.3,
                "feelslikemin": 21.2,
                "feelslike": 22.3,
                "dew": 20,
                "humidity": 86.7,
                "precip": 6.7,
                "precipprob": 74.2,
                "precipcover": 58.33,
                "preciptype": [
                    "rain"
                ],
                "snow": 0,
                "snowdepth": 0,
                "windgust": 28.1,
                "windspeed": 9,
                "winddir": 118.7,
                "pressure": 1016.4,
                "cloudcover": 98.5,
                "visibility": 19.3,
                "solarradiation": 72.4,
                "solarenergy": 6.4,
                "uvindex": 3,
                "severerisk": 10,
                "sunrise": "05:56:16",
                "sunriseEpoch": 1728856576,
                "sunset": "17:23:30",
                "sunsetEpoch": 1728897810,
                "moonphase": 0.39,
                "conditions": "Rain, Overcast",
                "description": "Cloudy skies throughout the day with a chance of rain.",
                "icon": "rain",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-15",
                "datetimeEpoch": 1728921600,
                "tempmax": 21.2,
                "tempmin": 20.2,
                "temp": 20.6,
                "feelslikemax": 21.2,
                "feelslikemin": 20.2,
                "feelslike": 20.6,
                "dew": 19.9,
                "humidity": 95.4,
                "precip": 16.6,
                "precipprob": 77.4,
                "precipcover": 29.17,
                "preciptype": [
                    "rain"
                ],
                "snow": 0,
                "snowdepth": 0,
                "windgust": 16.6,
                "windspeed": 9.4,
                "winddir": 21.4,
                "pressure": 1016.7,
                "cloudcover": 96.8,
                "visibility": 18.3,
                "solarradiation": 17.1,
                "solarenergy": 1.2,
                "uvindex": 1,
                "severerisk": 10,
                "sunrise": "05:56:57",
                "sunriseEpoch": 1728943017,
                "sunset": "17:22:22",
                "sunsetEpoch": 1728984142,
                "moonphase": 0.42,
                "conditions": "Rain, Overcast",
                "description": "Cloudy skies throughout the day with a chance of rain throughout the day.",
                "icon": "rain",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-16",
                "datetimeEpoch": 1729008000,
                "tempmax": 24,
                "tempmin": 20.8,
                "temp": 22.1,
                "feelslikemax": 24,
                "feelslikemin": 20.8,
                "feelslike": 22.1,
                "dew": 20.2,
                "humidity": 89.4,
                "precip": 2.1,
                "precipprob": 74.2,
                "precipcover": 16.67,
                "preciptype": [
                    "rain"
                ],
                "snow": 0,
                "snowdepth": 0,
                "windgust": 22.7,
                "windspeed": 12.6,
                "winddir": 73.9,
                "pressure": 1017.5,
                "cloudcover": 86.7,
                "visibility": 22.1,
                "solarradiation": 102.9,
                "solarenergy": 9,
                "uvindex": 4,
                "severerisk": 10,
                "sunrise": "05:57:39",
                "sunriseEpoch": 1729029459,
                "sunset": "17:21:14",
                "sunsetEpoch": 1729070474,
                "moonphase": 0.46,
                "conditions": "Rain, Partially cloudy",
                "description": "Partly cloudy throughout the day with rain in the morning and afternoon.",
                "icon": "rain",
                "stations": null,
                "source": "fcst"
            },
            {
                "datetime": "2024-10-17",
                "datetimeEpoch": 1729094400,
                "tempmax": 24.9,
                "tempmin": 21,
                "temp": 20.2,
                "feelslikemax": 24.9,
                "feelslikemin": 21,
                "feelslike": 22.2,
                "dew": 20.7,
                "humidity": 90.9,
                "precip": 5,
                "precipprob": 61.3,
                "precipcover": 20.83,
                "preciptype": [
                    "rain"
                ],
                "snow": 0,
                "snowdepth": 0,
                "windgust": 25.2,
                "windspeed": 8.3,
                "winddir": 206.4,
                "pressure": 1013.8,
                "cloudcover": 92.6,
                "visibility": 21.8,
                "solarradiation": 88.5,
                "solarenergy": 7.8,
                "uvindex": 4,
                "severerisk": 10,
                "sunrise": "05:58:21",
                "sunriseEpoch": 1729115901,
                "sunset": "17:20:07",
                "sunsetEpoch": 1729156807,
                "moonphase": 0.5,
                "conditions": "Rain, Overcast",
                "description": "Cloudy skies throughout the day with a chance of rain.",
                "icon": "rain",
                "stations": null,
                "source": "fcst"
            }
        ],
        "stations": {
            "ZSSS": {
                "distance": 15109,
                "latitude": 31.2,
                "longitude": 121.33,
                "useCount": 0,
                "id": "ZSSS",
                "name": "ZSSS",
                "quality": 50,
                "contribution": 0
            },
            "ZSPD": {
                "distance": 31871,
                "latitude": 31.12,
                "longitude": 121.77,
                "useCount": 0,
                "id": "ZSPD",
                "name": "ZSPD",
                "quality": 50,
                "contribution": 0
            }
        }
    }
""".trimIndent()
